package eap.pli24.rastaman.ui;

import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;

/**
 *
 * @author Apostolis Iakovakis
 * @author Nikos Karagiannis
 * @author Nikos Krommydas
 * @author Malamas Malamidis
 */
public class HeaderPanel extends javax.swing.JPanel {

    /**
     * Creates new form HeaderPanel
     */
    public HeaderPanel() {
        initComponents();
        initFurther();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new Box.Filler(new Dimension(15, 5), new Dimension(15, 5), new Dimension(15, 5));
        headerLabel = new JLabel();

        setLayout(new BoxLayout(this, BoxLayout.LINE_AXIS));
        add(filler1);

        headerLabel.setPreferredSize(new Dimension(0, 30));
        add(headerLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Box.Filler filler1;
    private JLabel headerLabel;
    // End of variables declaration//GEN-END:variables
    //
    // Ο δικός μας κώδικας αρχίζει εδώ, για να είναι
    // εμφανώς διαχωρισμένος από τον αυτόματα δημιουργούμενο
    //

    public void setHeaderLabel(String text) {
        headerLabel.setText(text);
    }

    private void initFurther() {
        setPreferredSize(new Dimension(0, UIProperties.HEADER_HEIGHT));
        setBackground(UIProperties.HEADER_BACKGROUND);
        headerLabel.setFont(UIProperties.HEADER_FONT);
        headerLabel.setForeground(UIProperties.HEADER_FOREGROUND);
    }
}
