/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eap.pli24.rastaman.ui;

import eap.pli24.rastaman.entities.Album;
import eap.pli24.rastaman.entities.Musicgroup;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.Beans;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author malamas
 */
public class GroupTablePanel extends javax.swing.JPanel {

    /**
     * Creates new form ArtistTablePanel
     */
    public GroupTablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        RastamanPUEntityManager0 = Beans.isDesignTime() ? null : Persistence.createEntityManagerFactory("RastamanPU").createEntityManager();
        musicgroupQuery = Beans.isDesignTime() ? null : RastamanPUEntityManager0.createQuery("SELECT m FROM Musicgroup m");
        musicgroupList = Beans.isDesignTime() ? Collections.emptyList() : musicgroupQuery.getResultList();
        albumQuery = Beans.isDesignTime() ? null : RastamanPUEntityManager0.createQuery("SELECT a FROM Album a");
        albumList = Beans.isDesignTime() ? Collections.emptyList() : albumQuery.getResultList();
        musicgroupQuery2 = Beans.isDesignTime() ? null : RastamanPUEntityManager0.createQuery("SELECT m FROM Musicgroup m");
        musicgroupList2 = Beans.isDesignTime() ? Collections.emptyList() : musicgroupQuery2.getResultList();
        jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        jButton1 = new JButton();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();

        setLayout(new BorderLayout());

        jLabel1.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Συγκροτήματα");
        jLabel1.setPreferredSize(new Dimension(0, 30));
        add(jLabel1, BorderLayout.PAGE_START);

        jPanel1.setLayout(new BorderLayout());

        jButton1.setText("Πίσω");
        jButton1.setPreferredSize(new Dimension(80, 23));
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, BorderLayout.LINE_END);

        add(jPanel1, BorderLayout.PAGE_END);

        JTableBinding jTableBinding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE, musicgroupList2, jTable1);
        JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${albumList}"));
        columnBinding.setColumnName("Album List");
        columnBinding.setColumnClass(List.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${artistList}"));
        columnBinding.setColumnName("Artist List");
        columnBinding.setColumnClass(List.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${formationdate}"));
        columnBinding.setColumnName("Formationdate");
        columnBinding.setColumnClass(Date.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${musicgroupid}"));
        columnBinding.setColumnName("Musicgroupid");
        columnBinding.setColumnClass(Long.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.hidePanel(this);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private EntityManager RastamanPUEntityManager0;
    private List<Album> albumList;
    private Query albumQuery;
    private JButton jButton1;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    private List<Musicgroup> musicgroupList;
    private List<Musicgroup> musicgroupList2;
    private Query musicgroupQuery;
    private Query musicgroupQuery2;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    //
    // Ο δικός μας κώδικας αρχίζει εδώ, για να είναι
    // εμφανώς διαχωρισμένος από τον αυτόματα δημιουργούμενο
    //
    private MainFrameController controller;

    public void setController(MainFrameController controller) {
        this.controller = controller;
    }
}
