package eap.pli24.rastaman.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Malamas Malamidis
 */
public class SideBarPanel extends javax.swing.JPanel {

    /**
     * Creates new form SideBarPanel
     */
    public SideBarPanel() {
        initComponents();
        initFurther();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new Box.Filler(new Dimension(10, 20), new Dimension(10, 20), new Dimension(10, 20));
        rastamanLabel = new JLabel();

        setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        add(filler1);

        rastamanLabel.setHorizontalAlignment(SwingConstants.CENTER);
        rastamanLabel.setIcon(new ImageIcon(getClass().getResource("/eap/pli24/rastaman/resources/images/rastaman_200x200.png"))); // NOI18N
        rastamanLabel.setVerticalAlignment(SwingConstants.TOP);
        rastamanLabel.setAlignmentX(0.5F);
        rastamanLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        rastamanLabel.setVerticalTextPosition(SwingConstants.BOTTOM);
        add(rastamanLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Box.Filler filler1;
    private JLabel rastamanLabel;
    // End of variables declaration//GEN-END:variables
    //
    // Ο δικός μας κώδικας αρχίζει εδώ, για να είναι
    // εμφανώς διαχωρισμένος από τον αυτόματα δημιουργούμενο
    //
    private static final int PANEL_WIDTH = 240;

    private void initFurther() {
        this.setPreferredSize(new Dimension(PANEL_WIDTH, 0));
        this.setBackground(new Color(102, 102, 0));

        rastamanLabel.setPreferredSize(new Dimension(PANEL_WIDTH, 0));

        rastamanLabel.setFont(new Font("Tahoma", 1, 14));
        rastamanLabel.setForeground(new Color(240, 213, 44));
        rastamanLabel.setText("Rastaman!");
    }
}
