package eap.pli24.rastaman.ui;

import java.awt.Dimension;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Apostolis Iakovakis
 * @author Nikos Karagiannis
 * @author Nikos Krommydas
 * @author Malamas Malamidis
 */
public class SideBarPanel extends javax.swing.JPanel {

    private static final Logger LOGGER = Logger.getLogger(MainFrameController.class.getName());

    /**
     * Creates new form SideBarPanel
     */
    public SideBarPanel() {
        initComponents();
        initFurther();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new Box.Filler(new Dimension(20, 20), new Dimension(20, 20), new Dimension(20, 20));
        rastamanLabel = new JLabel();
        filler2 = new Box.Filler(new Dimension(20, 40), new Dimension(20, 40), new Dimension(20, 40));
        creditsLabel = new JLabel();
        filler3 = new Box.Filler(new Dimension(20, 30), new Dimension(20, 30), new Dimension(20, 30));

        setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        add(filler1);

        rastamanLabel.setHorizontalAlignment(SwingConstants.CENTER);
        rastamanLabel.setIcon(new ImageIcon(getClass().getResource("/eap/pli24/rastaman/resources/images/rastaman_200x200.png"))); // NOI18N
        rastamanLabel.setVerticalAlignment(SwingConstants.TOP);
        rastamanLabel.setAlignmentX(0.5F);
        rastamanLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        rastamanLabel.setVerticalTextPosition(SwingConstants.BOTTOM);
        add(rastamanLabel);
        add(filler2);

        creditsLabel.setVerticalAlignment(SwingConstants.TOP);
        creditsLabel.setAlignmentX(0.5F);
        creditsLabel.setMaximumSize(new Dimension(20, 20));
        creditsLabel.setVerticalTextPosition(SwingConstants.TOP);
        add(creditsLabel);
        add(filler3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel creditsLabel;
    private Box.Filler filler1;
    private Box.Filler filler2;
    private Box.Filler filler3;
    private JLabel rastamanLabel;
    // End of variables declaration//GEN-END:variables
    //
    // Ο δικός μας κώδικας αρχίζει εδώ, για να είναι
    // εμφανώς διαχωρισμένος από τον αυτόματα δημιουργούμενο
    //

    private void initFurther() {
        this.setPreferredSize(new Dimension(UIProperties.SIDEBAR_WIDTH, 0));
        this.setBackground(UIProperties.SIDEBAR_BACKGROUND);

        rastamanLabel.setFont(UIProperties.RASTAMAN_FONT);
        rastamanLabel.setForeground(UIProperties.RASTAMAN_FOREGROUND);
        String rastaman = "Rastaman!";
        //String rastaman = "<html><font color=#55a035>Ra</font>"
        //        + "<font color=#f0d52c>sta</font>"
        //       + "<font color=#ff8855>man!</font>";
        rastamanLabel.setText(rastaman);

        String credits = "<html>a RAdio STAtion MANager application<br>"
                + "<br>"
                + "© 2015<br>"
                + "Αποστόλης Ιακωβάκης<br>"
                + "Νίκος Καραγιάννης<br>"
                + "Νίκος Κρομμύδας<br>"
                + "Μάλαμας Μαλαμίδης";
        creditsLabel.setMaximumSize(UIProperties.CREDITS_SIZE);
        creditsLabel.setFont(UIProperties.CREDITS_FONT);
        creditsLabel.setForeground(UIProperties.CREDITS_FOREGROUND);
        creditsLabel.setText(credits);
    }
}
