DROP TABLE PLAYLIST_SONG;
DROP TABLE PLAYLIST;
DROP TABLE Song;
DROP TABLE Album;
DROP TABLE Artist_MusicGroup;
DROP TABLE Artist;
DROP TABLE MusicGroup;
DROP TABLE Label;
DROP TABLE MusicGenre;

CREATE TABLE MusicGenre (
  musicGenreID integer GENERATED BY DEFAULT AS IDENTITY, 
  name         varchar(20) NOT NULL, 
  PRIMARY KEY (musicGenreID)
);

CREATE TABLE Label (
  labelID   bigint GENERATED BY DEFAULT AS IDENTITY, 
  name      varchar(50) NOT NULL, 
  address   varchar(50), 
  telephone varchar(10), 
  PRIMARY KEY (labelID)
);

CREATE TABLE MusicGroup (
  musicGroupID  bigint GENERATED BY DEFAULT AS IDENTITY, 
  name          varchar(50) NOT NULL, 
  formationDate date, 
  PRIMARY KEY (musicGroupID)
);

CREATE TABLE Artist (
  ArtistID     bigint GENERATED BY DEFAULT AS IDENTITY, 
  lastName     varchar(50), 
  firstName    varchar(50), 
  artisticName varchar(50), 
  sex          varchar(1) NOT NULL, 
  birthDay     date, 
  birthPlace   varchar(100), 
  musciGenreID integer NOT NULL, 
  PRIMARY KEY (ArtistID),
  FOREIGN KEY (musciGenreID) REFERENCES MusicGenre (musicGenreID) ON DELETE Restrict
);

CREATE TABLE Artist_MusicGroup (
  ArtistArtistID         bigint NOT NULL, 
  MusicGroupmusicGroupID bigint NOT NULL, 
  PRIMARY KEY (ArtistArtistID, MusicGroupmusicGroupID),
  FOREIGN KEY (MusicGroupmusicGroupID) REFERENCES MusicGroup (musicGroupID) ON DELETE Cascade,
  FOREIGN KEY (ArtistArtistID) REFERENCES Artist (ArtistID) ON DELETE Restrict
);

CREATE TABLE Album (
  albumID                bigint GENERATED BY DEFAULT AS IDENTITY, 
  title                  varchar(100) NOT NULL, 
  labelID                bigint NOT NULL, 
  releaseDate            date, 
  type                   varchar(2) NOT NULL, 
  diskNumber             integer DEFAULT 1 NOT NULL, 
  ArtistArtistID         bigint, 
  MusicGroupmusicGroupID bigint, 
  PRIMARY KEY (albumID),
  FOREIGN KEY (MusicGroupmusicGroupID) REFERENCES MusicGroup (musicGroupID) ON DELETE Restrict,
  FOREIGN KEY (ArtistArtistID) REFERENCES Artist (ArtistID) ON DELETE Restrict,
  FOREIGN KEY (labelID) REFERENCES Label (labelID) ON DELETE Restrict
);

CREATE TABLE Song (
  songID   bigint GENERATED BY DEFAULT AS IDENTITY, 
  title    varchar(50) NOT NULL, 
  duration integer NOT NULL, 
  trackNr  integer NOT NULL, 
  AlbumID  bigint NOT NULL, 
  PRIMARY KEY (songID),
  FOREIGN KEY (AlbumID) REFERENCES Album (albumID) ON DELETE Cascade
);

CREATE TABLE PLAYLIST (
  PLAYLIST_ID      BIGINT GENERATED BY DEFAULT AS IDENTITY, 
  NAME             VARCHAR(100) NOT NULL, 
  CREATION_DATE    DATE NOT NULL, 
  PRIMARY KEY (PLAYLIST_ID)
);

CREATE TABLE PLAYLIST_SONG (
  PLAYLIST_SONG_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
  PLAYLIST_ID      BIGINT NOT NULL,
  SLOT             INTEGER NOT NULL,    
  SONG_ID          BIGINT NOT NULL, 
  PRIMARY KEY (PLAYLIST_SONG_ID),
  FOREIGN KEY (SONG_ID) REFERENCES Song (songID) ON DELETE Restrict,
  FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST (PLAYLIST_ID) ON DELETE CASCADE
);
