DROP TABLE Playlist_Song;
DROP TABLE Playlist;
DROP TABLE Song;
DROP TABLE Album;
DROP TABLE Artist_Music_group;
DROP TABLE Artist;
DROP TABLE Music_group;
DROP TABLE Label;
DROP TABLE Genre;

CREATE TABLE Genre (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    name            VARCHAR(50) NOT NULL, 
    PRIMARY KEY (id)
);

CREATE TABLE Label (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    name            VARCHAR(100) NOT NULL, 
    address         VARCHAR(100), 
    telephone_no    VARCHAR(20), 
    PRIMARY KEY (id)
);

CREATE TABLE Music_group (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    name            VARCHAR(50) NOT NULL, 
    formation_date  DATE, 
    PRIMARY KEY (id)
);

CREATE TABLE Artist (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    last_name       VARCHAR(50), 
    first_name      VARCHAR(50), 
    artistic_name   VARCHAR(50), 
    gender          VARCHAR(1) NOT NULL, 
    birth_date      DATE, 
    birth_place     VARCHAR(100), 
    genre_id        BIGINT NOT NULL, 
    PRIMARY KEY (id),
    FOREIGN KEY (genre_id) REFERENCES Genre (id) ON DELETE RESTRICT
);

CREATE TABLE Artist_Music_group (
    artist_id       BIGINT NOT NULL, 
    music_group_id  BIGINT NOT NULL, 
    PRIMARY KEY (artist_id, music_group_id),
    FOREIGN KEY (music_group_id) REFERENCES Music_group (id) ON DELETE CASCADE,
    FOREIGN KEY (artist_id) REFERENCES Artist (id) ON DELETE RESTRICT
);

CREATE TABLE Album (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    title           VARCHAR(100) NOT NULL, 
    label_id        BIGINT NOT NULL, 
    release_date    DATE, 
    type            VARCHAR(2) NOT NULL, 
    disk_no         INTEGER DEFAULT 1 NOT NULL, 
    artist_id       BIGINT, 
    music_group_id  BIGINT, 
    PRIMARY KEY (id),
    FOREIGN KEY (music_group_id) REFERENCES Music_group (id) ON DELETE RESTRICT,
    FOREIGN KEY (artist_id) REFERENCES Artist (id) ON DELETE RESTRICT,
    FOREIGN KEY (label_id) REFERENCES Label (id) ON DELETE RESTRICT
);

CREATE TABLE Song (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    title           VARCHAR(100) NOT NULL, 
    duration        INTEGER NOT NULL, 
    track_no        INTEGER NOT NULL, 
    album_id        BIGINT NOT NULL, 
    PRIMARY KEY (id),
    FOREIGN KEY (album_id) REFERENCES Album (id) ON DELETE CASCADE
);

CREATE TABLE Playlist (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    name            VARCHAR(100) NOT NULL, 
    creation_date   DATE NOT NULL, 
    PRIMARY KEY (id)
);

CREATE TABLE Playlist_Song (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    playlist_id     BIGINT NOT NULL,
    slot            INTEGER NOT NULL,    
    song_id         BIGINT NOT NULL, 
    PRIMARY KEY (id),
    FOREIGN KEY (song_id) REFERENCES Song (id) ON DELETE RESTRICT,
    FOREIGN KEY (playlist_id) REFERENCES Playlist (id) ON DELETE CASCADE
);
