DROP TABLE PlayList_Song;
DROP TABLE Song;
DROP TABLE Album;
DROP TABLE PlayList;
DROP TABLE Artist_MusicGroup;
DROP TABLE Artist;
DROP TABLE MusicGroup;
DROP TABLE Label;
DROP TABLE MusicGenre;

CREATE TABLE MusicGenre (
  musicGenreID integer GENERATED BY DEFAULT AS IDENTITY, 
  name         varchar(20) NOT NULL, 
  PRIMARY KEY (musicGenreID)
);

CREATE TABLE Label (
  labelID   bigint GENERATED BY DEFAULT AS IDENTITY, 
  name      varchar(50) NOT NULL, 
  address   varchar(50), 
  telephone varchar(10), 
  PRIMARY KEY (labelID)
);

CREATE TABLE MusicGroup (
  musicGroupID  bigint GENERATED BY DEFAULT AS IDENTITY, 
  name          varchar(50) NOT NULL, 
  formationDate date, 
  PRIMARY KEY (musicGroupID)
);

CREATE TABLE Artist (
  ArtistID     bigint GENERATED BY DEFAULT AS IDENTITY, 
  firstName    varchar(20) NOT NULL, 
  lastName     varchar(50) NOT NULL, 
  artisticName varchar(50) NOT NULL, 
  sex          varchar(1) NOT NULL, 
  birthDay     date, 
  birthPlace   varchar(50), 
  musciGenreID integer NOT NULL, 
  PRIMARY KEY (ArtistID),
  FOREIGN KEY (musciGenreID) REFERENCES MusicGenre (musicGenreID) ON DELETE Restrict
);

CREATE TABLE Artist_MusicGroup (
  ArtistArtistID         bigint NOT NULL, 
  MusicGroupmusicGroupID bigint NOT NULL, 
  PRIMARY KEY (ArtistArtistID, MusicGroupmusicGroupID),
  FOREIGN KEY (MusicGroupmusicGroupID) REFERENCES MusicGroup (musicGroupID) ON DELETE Cascade,
  FOREIGN KEY (ArtistArtistID) REFERENCES Artist (ArtistID) ON DELETE Restrict
);

CREATE TABLE PlayList (
  playListID   bigint GENERATED BY DEFAULT AS IDENTITY, 
  name         varchar(100) NOT NULL, 
  creationDate date NOT NULL, 
  PRIMARY KEY (playListID)
);

CREATE TABLE Album (
  albumID                bigint GENERATED BY DEFAULT AS IDENTITY, 
  title                  varchar(100) NOT NULL, 
  labelID                bigint NOT NULL, 
  releaseDate            date, 
  type                   varchar(2) NOT NULL, 
  diskNumber             integer DEFAULT 1 NOT NULL, 
  ArtistArtistID         bigint, 
  MusicGroupmusicGroupID bigint, 
  PRIMARY KEY (albumID),
  FOREIGN KEY (MusicGroupmusicGroupID) REFERENCES MusicGroup (musicGroupID) ON DELETE Restrict,
  FOREIGN KEY (ArtistArtistID) REFERENCES Artist (ArtistID) ON DELETE Restrict,
  FOREIGN KEY (labelID) REFERENCES Label (labelID) ON DELETE Restrict
);

CREATE TABLE Song (
  songID   bigint GENERATED BY DEFAULT AS IDENTITY, 
  title    varchar(50) NOT NULL, 
  duration integer NOT NULL, 
  trackNr  integer NOT NULL, 
  AlbumID  bigint NOT NULL, 
  PRIMARY KEY (songID),
  FOREIGN KEY (AlbumID) REFERENCES Album (albumID) ON DELETE Cascade
);

CREATE TABLE PlayList_Song (
  PlayListplayListID bigint NOT NULL, 
  SongsongID         bigint NOT NULL, 
  PRIMARY KEY (PlayListplayListID,  SongsongID),
  FOREIGN KEY (SongsongID) REFERENCES Song (songID) ON DELETE Restrict,
  FOREIGN KEY (PlayListplayListID) REFERENCES PlayList (playListID) ON DELETE Cascade
);

CREATE INDEX Artist_firstName 
  ON Artist (firstName);
CREATE INDEX Artist_lastName 
  ON Artist (lastName);
CREATE INDEX PlayList_name 
  ON PlayList (name);
CREATE INDEX Song_title 
  ON Song (title);
CREATE UNIQUE INDEX Album_albumID 
  ON Album (albumID);
CREATE INDEX Album_title 
  ON Album (title);
CREATE UNIQUE INDEX Label_labelID 
  ON Label (labelID);
CREATE UNIQUE INDEX Label_name 
  ON Label (name);
